import Head from "next/head";
import Link from "next/link";
import Authorization from "@/components/Layout/Authorization";
import Navbar from "@/components/Navbar";
import MainPage from "./Main";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <Authorization>
      <Head>
        <title>Next JS FE 20</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />
        <MainPage />
        <Footer />
      </div>
    </Authorization>
  );
}
